#!/bin/bash
# Now we are under your project's subdirectory.
git clone "https://github.com/alphamarket/lizard.git" lizard || exit 1
# Delete this & README.md
rm -rf lizard/.git lizard/README.md lizard/lizard-setup lizard/demo.gif lizard/LICENCE
# reset stage and add lizard folder
git reset && git add lizard
# commit the lizard
git commit -m "+ lizard/"

